import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { BookOpen, Clock, Star, ArrowRight, PlayCircle } from 'lucide-react';
import VideoPlayer from '@/components/VideoPlayer';

interface Course {
  id: number;
  title: string;
  description: string;
  modules: string;
  difficulty: string;
}

export default function Courses() {
  const [courses, setCourses] = useState<Course[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedCourse, setSelectedCourse] = useState<Course | null>(null);

  useEffect(() => {
    fetch('/api/courses')
      .then(res => res.json())
      .then(data => {
        setCourses(data);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to fetch courses", err);
        setLoading(false);
      });
  }, []);

  const handleStartCourse = (course: Course) => {
    if (course.title.includes("Quantum")) {
      setSelectedCourse(course);
    } else {
      // For other courses, maybe show a "Coming Soon" or different action
      alert("Video content for this course is currently being generated by the AI.");
    }
  };

  if (loading) {
    return <div className="text-center text-slate-400 mt-20 animate-pulse">Loading neural modules...</div>;
  }

  return (
    <div className="space-y-8 relative">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-3xl font-bold text-white mb-2 font-display">Available Courses</h2>
          <p className="text-slate-400">Expand your neural network with new knowledge nodes.</p>
        </div>
        <div className="flex gap-2">
          <input 
            type="text" 
            placeholder="Search modules..." 
            className="bg-black/20 border border-white/10 rounded-lg px-4 py-2 text-sm text-slate-200 outline-none focus:border-cyan-500/50 w-64 transition-all focus:w-72"
          />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {courses.map((course, index) => (
          <motion.div
            key={course.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="group relative bg-white/5 border border-white/10 rounded-2xl overflow-hidden hover:border-cyan-500/30 transition-all duration-300 hover:shadow-[0_0_30px_rgba(6,182,212,0.15)]"
          >
            <div className="absolute inset-0 bg-gradient-to-b from-transparent to-black/80 z-0" />
            
            {/* Image Placeholder */}
            <div className="h-48 bg-slate-800 relative z-[-1] overflow-hidden">
               <img 
                 src={`https://picsum.photos/seed/${course.title}/800/600`} 
                 alt={course.title}
                 className="w-full h-full object-cover opacity-60 group-hover:scale-110 transition-transform duration-700"
                 referrerPolicy="no-referrer"
               />
               <div className="absolute inset-0 bg-cyan-500/10 opacity-0 group-hover:opacity-100 transition-opacity duration-300 mix-blend-overlay" />
            </div>

            <div className="p-6 relative z-10">
              <div className="flex justify-between items-start mb-4">
                <span className={`px-2 py-1 rounded text-xs font-medium border backdrop-blur-sm ${
                  course.difficulty === 'Hard' ? 'bg-red-500/10 text-red-400 border-red-500/20' :
                  course.difficulty === 'Medium' ? 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20' :
                  'bg-green-500/10 text-green-400 border-green-500/20'
                }`}>
                  {course.difficulty}
                </span>
                <div className="flex items-center gap-1 text-yellow-400 bg-black/40 px-2 py-1 rounded-full border border-white/5">
                  <Star className="w-3 h-3 fill-current" />
                  <span className="text-xs font-medium">4.8</span>
                </div>
              </div>

              <h3 className="text-xl font-bold text-white mb-2 group-hover:text-cyan-400 transition-colors font-display">
                {course.title}
              </h3>
              <p className="text-slate-400 text-sm mb-4 line-clamp-2 leading-relaxed">
                {course.description}
              </p>

              <div className="flex items-center justify-between mt-4 pt-4 border-t border-white/10">
                <div className="flex items-center gap-2 text-slate-500 text-xs font-mono">
                  <Clock className="w-3 h-3" />
                  <span>4h 30m</span>
                </div>
                <button 
                  onClick={() => handleStartCourse(course)}
                  className="flex items-center gap-2 text-cyan-400 text-sm font-medium group-hover:translate-x-1 transition-transform hover:text-cyan-300"
                >
                  {course.title.includes("Quantum") ? (
                    <>
                      <PlayCircle className="w-4 h-4" />
                      Watch Video
                    </>
                  ) : (
                    <>
                      Start Module
                      <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </button>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Video Player Modal */}
      <AnimatePresence>
        {selectedCourse && (
          <VideoPlayer 
            src="https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" 
            title={selectedCourse.title} 
            onClose={() => setSelectedCourse(null)} 
          />
        )}
      </AnimatePresence>
    </div>
  );
}
